# secrets.json.gpg ecryption phrase is github-actions
name: Encryped Files
on: push
jobs:
  decrypt-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt File
        env:
          PASSPHRASE: ${{secrets.FILE_PASSPHRASE}}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/decrypted-secrets.json secrets.json.gpg
      - name: Print File Content
        run: cat $HOME/decrypted-secrets.json
